# Generated by Django 2.2 on 2021-03-15 20:56

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('organizer', 'Organizer')], default='organizer', max_length=100)),
                ('location', models.CharField(choices=[('Zamfara State', 'Zamfara State'), ('Yobe State', 'Yobe State'), ('Taraba State', 'Taraba State'), ('Sokoto State', 'Sokoto State'), ('Rivers State', 'Rivers State'), ('Plateau State', 'Plateau State'), ('Oyo State', 'Oyo State'), ('Osun State', 'Osun State'), ('Ondo State', 'Ondo State'), ('Ogun State', 'Ogun State'), ('Niger State', 'Niger State'), ('Nasarawa State', 'Nasarawa State'), ('Lagos State', 'Lagos State'), ('Kwara State', 'Kwara State'), ('Kogi State', 'Kogi State'), ('Kebbi State', 'Kebbi State'), ('Katsina State', 'Katsina State'), ('Kano State', 'Kano State'), ('Kaduna State', 'Kaduna State'), ('Jigawa State', 'Jigawa State'), ('Imo State', 'Imo State'), ('Gombe State', 'Gombe State'), ('Federal Capital Territory', 'Federal Capital Territory'), ('Enugu State', 'Enugu State'), ('Ekiti State', 'Ekiti State'), ('Edo', 'Edo'), ('Ebonyi State', 'Ebonyi State'), ('Delta State', 'Delta State'), ('Cross River State', 'Cross River State'), ('Borno State', 'Borno State'), ('Benue State', 'Benue State'), ('Bayelsa State', 'Bayelsa State'), ('Bauchi State', 'Bauchi State'), ('Anambra State', 'Anambra State'), ('Akwa Ibom State', 'Akwa Ibom State'), ('Adamawa State', 'Adamawa State'), ('Abia State', 'Abia State')], default='Lagos State', max_length=100)),
                ('phone_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='this field must be a  valid phone number 📱 !', regex='(\\d{3})\\D*(\\d{3})\\D*(\\d{4})\\D*(\\d*)$')])),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('price', models.DecimalField(decimal_places=3, max_digits=100)),
                ('street_address', models.CharField(max_length=200)),
                ('email_adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_email', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('organizer', 'Organizer')], default='user', max_length=100)),
                ('location', models.CharField(choices=[('Zamfara State', 'Zamfara State'), ('Yobe State', 'Yobe State'), ('Taraba State', 'Taraba State'), ('Sokoto State', 'Sokoto State'), ('Rivers State', 'Rivers State'), ('Plateau State', 'Plateau State'), ('Oyo State', 'Oyo State'), ('Osun State', 'Osun State'), ('Ondo State', 'Ondo State'), ('Ogun State', 'Ogun State'), ('Niger State', 'Niger State'), ('Nasarawa State', 'Nasarawa State'), ('Lagos State', 'Lagos State'), ('Kwara State', 'Kwara State'), ('Kogi State', 'Kogi State'), ('Kebbi State', 'Kebbi State'), ('Katsina State', 'Katsina State'), ('Kano State', 'Kano State'), ('Kaduna State', 'Kaduna State'), ('Jigawa State', 'Jigawa State'), ('Imo State', 'Imo State'), ('Gombe State', 'Gombe State'), ('Federal Capital Territory', 'Federal Capital Territory'), ('Enugu State', 'Enugu State'), ('Ekiti State', 'Ekiti State'), ('Edo', 'Edo'), ('Ebonyi State', 'Ebonyi State'), ('Delta State', 'Delta State'), ('Cross River State', 'Cross River State'), ('Borno State', 'Borno State'), ('Benue State', 'Benue State'), ('Bayelsa State', 'Bayelsa State'), ('Bauchi State', 'Bauchi State'), ('Anambra State', 'Anambra State'), ('Akwa Ibom State', 'Akwa Ibom State'), ('Adamawa State', 'Adamawa State'), ('Abia State', 'Abia State')], default='Lagos State', max_length=100)),
                ('phone_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='this field must be a  valid phone number 📱 !', regex='(\\d{3})\\D*(\\d{3})\\D*(\\d{4})\\D*(\\d*)$')])),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('email_adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_email_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
