# Generated by Django 2.2 on 2021-03-16 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210316_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerprofile',
            name='supplementary_phone_number',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='this field must be a  valid phone number 📱 !', regex='(\\d{3})\\D*(\\d{3})\\D*(\\d{4})\\D*(\\d*)$')]),
        ),
        migrations.AlterField(
            model_name='eventuserprofile',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='this field must be a  valid phone number 📱 !', regex='(\\d{3})\\D*(\\d{3})\\D*(\\d{4})\\D*(\\d*)$')]),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='this field must be a  valid phone number 📱 !', regex='(\\d{3})\\D*(\\d{3})\\D*(\\d{4})\\D*(\\d*)$')]),
        ),
    ]
