# Generated by Django 2.2 on 2021-02-18 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_eventuser_organizeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUserProfile',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auth_user_event', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='this field must be a phone number 📱 !', regex='(\\d{3})\\D*(\\d{3})\\D*(\\d{4})\\D*(\\d*)$')])),
                ('profile_photo', models.ImageField(blank=True, upload_to='user/')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auth_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='this field must be a phone number 📱 !', regex='(\\d{3})\\D*(\\d{3})\\D*(\\d{4})\\D*(\\d*)$')])),
                ('description', models.TextField()),
                ('event_photo', models.ImageField(blank=True, upload_to='photos/')),
                ('price', models.DecimalField(decimal_places=3, max_digits=100)),
                ('street_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='EventUser',
        ),
        migrations.DeleteModel(
            name='OrganizerUser',
        ),
        migrations.AddField(
            model_name='authuser',
            name='location',
            field=models.CharField(choices=[('Zamfara State', 'Zamfara State'), ('Yobe State', 'Yobe State'), ('Taraba State', 'Taraba State'), ('Sokoto State', 'Sokoto State'), ('Rivers State', 'Rivers State'), ('Plateau State', 'Plateau State'), ('Oyo State', 'Oyo State'), ('Osun State', 'Osun State'), ('Ondo State', 'Ondo State'), ('Ogun State', 'Ogun State'), ('Niger State', 'Niger State'), ('Nasarawa State', 'Nasarawa State'), ('Lagos State', 'Lagos State'), ('Kwara State', 'Kwara State'), ('Kogi State', 'Kogi State'), ('Kebbi State', 'Kebbi State'), ('Katsina State', 'Katsina State'), ('Kano State', 'Kano State'), ('Kaduna State', 'Kaduna State'), ('Jigawa State', 'Jigawa State'), ('Imo State', 'Imo State'), ('Gombe State', 'Gombe State'), ('Federal Capital Territory', 'Federal Capital Territory'), ('Enugu State', 'Enugu State'), ('Ekiti State', 'Ekiti State'), ('Edo', 'Edo'), ('Ebonyi State', 'Ebonyi State'), ('Delta State', 'Delta State'), ('Cross River State', 'Cross River State'), ('Borno State', 'Borno State'), ('Benue State', 'Benue State'), ('Bayelsa State', 'Bayelsa State'), ('Bauchi State', 'Bauchi State'), ('Anambra State', 'Anambra State'), ('Akwa Ibom State', 'Akwa Ibom State'), ('Adamawa State', 'Adamawa State'), ('Abia State', 'Abia State')], default='Lagos State', max_length=100),
        ),
        migrations.AddField(
            model_name='authuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('organizer', 'Organizer')], default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='email_adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_email', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizerprofile',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventuserprofile',
            name='email_adress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_email_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventuserprofile',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_location_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
