# Generated by Django 2.2 on 2021-02-18 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210218_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuserprofile',
            name='phone_number',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='this field must be a  valid phone number 📱 !', regex='(\\d{3})\\D*(\\d{3})\\D*(\\d{4})\\D*(\\d*)$')]),
        ),
        migrations.AlterField(
            model_name='organizerprofile',
            name='phone_number',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='this field must be a  valid phone number 📱 !', regex='(\\d{3})\\D*(\\d{3})\\D*(\\d{4})\\D*(\\d*)$')]),
        ),
    ]
