# Generated by Django 2.2 on 2021-05-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210316_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotted_budget', models.DecimalField(decimal_places=3, max_digits=30)),
                ('date_of_event', models.DateField()),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('others', 'Others'), ('conferences', 'Conferences'), ('competitions', 'Competitions'), ('expo', 'Expo')], default='choose your event type here !', max_length=100)),
                ('estimated_no_of_guests', models.IntegerField()),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.EventUserProfile')),
            ],
        ),
    ]
