# Generated by Django 2.2 on 2021-05-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_userbookprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserBookProfile',
            new_name='UserBook',
        ),
    ]
