# Generated by Django 2.2 on 2021-05-25 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210525_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='email_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
