# Generated by Django 2.2 on 2021-05-25 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210525_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='email_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.EventUserProfile'),
        ),
    ]
