# Generated by Django 2.2 on 2021-05-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210525_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerprofile',
            name='email_address',
            field=models.CharField(max_length=50),
        ),
    ]
