# Generated by Django 2.2 on 2021-05-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_auto_20210526_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizerprofile',
            name='email_address',
            field=models.CharField(max_length=50),
        ),
    ]
