# Generated by Django 2.2 on 2021-06-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20210527_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
