# Generated by Django 2.2 on 2021-06-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_userbook_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='available',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=100),
        ),
    ]
