# Generated by Django 2.2 on 2021-06-02 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_auto_20210601_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuserprofile',
            name='email_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_email_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventuserprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
