# Generated by Django 2.2 on 2021-06-03 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20210602_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='email_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
