# Generated by Django 2.2 on 2021-06-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20210603_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
    ]
