# Generated by Django 2.2 on 2021-06-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20210603_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
