# Generated by Django 2.2 on 2021-06-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20210605_0602'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBook',
        ),
    ]
