# Generated by Django 2.2 on 2021-06-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_delete_userbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('allotted_budget', models.DecimalField(decimal_places=3, max_digits=30)),
                ('date_of_event', models.DateField()),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'Birthday'), ('others', 'Others'), ('conferences', 'Conferences'), ('competitions', 'Competitions'), ('expo', 'Expo')], default='choose your event type here !', max_length=100)),
                ('estimated_no_of_guests', models.IntegerField()),
                ('available', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=100)),
            ],
        ),
    ]
